/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversor.vista;

import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author leona
 */
public class frmPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        //this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panePrincipal = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        valorIngresado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        options = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cantidadRes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        valorTemp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tempOption = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        resTemp = new javax.swing.JTextField();
        btnTempSalir = new javax.swing.JButton();
        btnTempLimpiar = new javax.swing.JButton();
        btnConvTemp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(128, 141, 173));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Conversor de monedas");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 15, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Convierta pesos argentinos en cualquiera de las monedas disponibles");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ingrese la cantidad de pesos a convertir");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));
        jPanel4.add(valorIngresado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 210, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Seleccione el tipo de moneda");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        options.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion ...", "Pesos a Dolares", "Pesos a Euros", "Pesos a Libras Esterlinas", "Pesos a Won", "Pesos a Yen", "Dolares a Pesos", "Euros a Pesos", "Libras Esterlinas a Pesos", "Won a Pesos", "Yen a Pesos" }));
        jPanel4.add(options, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 210, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Resultado de la conversion:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));
        jPanel4.add(cantidadRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 210, -1));

        jButton1.setText("Convertir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 302, -1, 30));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel4.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 100, 30));

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 100, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conversor/images/Frame 13 (3).png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 290, 380));

        panePrincipal.addTab("Conversor de monedas", jPanel4);

        jPanel5.setBackground(new java.awt.Color(128, 141, 173));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Conversor de temperaturas");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Convierta una cantidad de temperatura en las unidades disponibles ");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 81, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese la temperatura a convertir");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));
        jPanel5.add(valorTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 210, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Selecciona la escala para convertir");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        tempOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion ...", "Celsius a Fahrenheit", "Celsius a Kelvin", "Fahrenheit a Celsius", "Fahrenheit a Kelvin", "Kelvin a Fahrenheit", "Kelvin a Celsius" }));
        tempOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempOptionActionPerformed(evt);
            }
        });
        jPanel5.add(tempOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 210, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Resultado de la conversion");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));
        jPanel5.add(resTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 210, -1));

        btnTempSalir.setText("Salir");
        btnTempSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempSalirActionPerformed(evt);
            }
        });
        jPanel5.add(btnTempSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 100, 30));

        btnTempLimpiar.setText("Limpiar");
        btnTempLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempLimpiarActionPerformed(evt);
            }
        });
        jPanel5.add(btnTempLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 100, 30));

        btnConvTemp.setText("Convertir");
        btnConvTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvTempActionPerformed(evt);
            }
        });
        jPanel5.add(btnConvTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conversor/images/Frame 13 (3).png"))); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 290, 380));

        panePrincipal.addTab("Conversor de temperaturas", jPanel5);

        getContentPane().add(panePrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents
// expresion regular para valores
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:   
        
        double dolar = 123.662647;
        double euro = 130.297663;
        double libra = 151.715896;
        double yen = 0.907179;
        double won = 0.095712;

        if ((valorIngresado.getText()).isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Ingrese un valor", "Error de validacion", JOptionPane.ERROR_MESSAGE);
        } else {
            
            if (((valorIngresado.getText()).matches("^\\d+(.\\d{1,2})?$"))) {
                
                double cantidadIngresada = Double.parseDouble(valorIngresado.getText());
                double valorCambiado = 0.0;
                boolean seleccion = true;
                
                switch(options.getSelectedItem().toString()) {
                    case "Pesos a Dolares": valorCambiado = cantidadIngresada / dolar; 
                        break;
                    case "Pesos a Euros": valorCambiado = cantidadIngresada / euro;
                        break;
                    case "Pesos a Libras Esterlinas": valorCambiado = cantidadIngresada / libra;
                        break;
                    case "Pesos a Yen": valorCambiado = cantidadIngresada / yen;
                        break;
                    case "Pesos a Won": valorCambiado = cantidadIngresada / won;
                        break;
                    case "Dolares a Pesos": valorCambiado = cantidadIngresada * dolar;
                        break;
                    case "Euros a Pesos": valorCambiado = cantidadIngresada * euro;
                        break;
                    case "Libras Esterlinas a Pesos": valorCambiado = cantidadIngresada * libra;
                        break;
                    case "Yen a Pesos": valorCambiado = cantidadIngresada * yen;
                        break;
                    case "Won a Pesos": valorCambiado = cantidadIngresada * won;
                        break;
                    default:
                        seleccion = false;
                }

                if (seleccion) {
                    String cantidadConvertida = String.format("%.5f", valorCambiado);
                    cantidadRes.setText(cantidadConvertida);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una opción", "Error de validacion", JOptionPane.ERROR_MESSAGE);
                }
                
            } else {
            JOptionPane.showMessageDialog(rootPane, "El valor ingresado debe coincidir con el formato solicitado", "Error de validacion", JOptionPane.ERROR_MESSAGE);
            }
        }          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        options.setSelectedIndex(0);
        valorIngresado.setText(null);
        cantidadRes.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConvTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvTempActionPerformed
        // TODO add your handling code here:
        
//            Para convertir de ºF a K use la fórmula: K = 5/9 (ºF – 32) + 273.15.
        
        if (( valorTemp.getText()).isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Ingrese un valor", "Error de validacion", JOptionPane.ERROR_MESSAGE);
        } else {
            
            if (((valorTemp.getText()).matches("^\\d+(.\\d{1,2})?$"))) {
                
                double cantidadIngresada = Double.parseDouble(valorTemp.getText());
                double valorCambiado = 0.0;
                boolean seleccion = true;
                
                switch(tempOption.getSelectedItem().toString()) {
                    case "Celsius a Fahrenheit": valorCambiado = (cantidadIngresada * 1.8) + 32; 
                        break;
                    case "Celsius a Kelvin": valorCambiado = cantidadIngresada + 273.15;
                        break;
                    case "Kelvin a Fahrenheit": valorCambiado = 1.8*(cantidadIngresada - 273.15) + 32;
                        break;
                    case "Kelvin a Celsius": valorCambiado = cantidadIngresada - 273.15;
                        break;
                    case "Fahrenheit a Celsius": valorCambiado = (cantidadIngresada - 32) / 1.8;
                        break;
                    case "Fahrenheit a Kelvin": valorCambiado = 5/9 * (cantidadIngresada - 32) + 273.15;
                        break;
                    default:
                        seleccion = false;
                }
                
                if (seleccion) {
                    String cantidadConvertida = String.format("%.5f", valorCambiado);
                    resTemp.setText(cantidadConvertida);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una opción", "Error de validacion", JOptionPane.ERROR_MESSAGE);
                }
                
            } else {
            JOptionPane.showMessageDialog(rootPane, "El valor ingresado debe coincidir con el formato solicitado", "Error de validacion", JOptionPane.ERROR_MESSAGE);
            }
        }                         
    }//GEN-LAST:event_btnConvTempActionPerformed

    private void tempOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempOptionActionPerformed

    private void btnTempLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempLimpiarActionPerformed
        // TODO add your handling code here:
        valorTemp.setText(null);
        resTemp.setText(null);
        tempOption.setSelectedIndex(0);
    }//GEN-LAST:event_btnTempLimpiarActionPerformed

    private void btnTempSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnTempSalirActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvTemp;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTempLimpiar;
    private javax.swing.JButton btnTempSalir;
    private javax.swing.JTextField cantidadRes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> options;
    private javax.swing.JTabbedPane panePrincipal;
    private javax.swing.JTextField resTemp;
    private javax.swing.JComboBox<String> tempOption;
    private javax.swing.JTextField valorIngresado;
    private javax.swing.JTextField valorTemp;
    // End of variables declaration//GEN-END:variables
}
